### ISSUE TITLE
The Terminal `localmobile` module must be included for this DiscoveryConfiguration

### ISSUE THREAD

**Issue by BaldDonkey2333** [stripe-samples/terminal-apps-on-devices#51]
discoverReaders -> LocalMobileDiscoveryConfiguration

com.stripe.stripeterminal.external.models.TerminalException: The Terminal `localmobile` module must be included for this DiscoveryConfiguration
                                                                                                    	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.getAdapterByDiscoveryConfiguration(ProxyAdapter.kt:225)
                                                                                                    	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.discoverReaders(ProxyAdapter.kt:197)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$DiscoverReadersOperation.executeIfNotCanceled(TerminalSession.kt:1910)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CancelableOperation.execute(TerminalSession.kt:1058)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:1016)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:875)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$6lM7341_XI6PEqXfOM-yc2U5tkQ(Unknown Source:0)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)

**Comment by mshafrir-stripe** [comment]
@BaldDonkey2333 if you are interested in Tap to Pay for Android, please refer to our documentation: https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay?platform=android

Tap to Pay is not compatible with Apps on Devices
